# general settings
name: BSRN_x4
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 1

# dataset and data loader settings
datasets:
  train:
    name: Flickr2K
    type: PairedImageDataset
    #dataroot_gt: H:\VOCCrop\Flickr2K\Flickr2K\Flickr2K_HR
    #dataroot_lq: H:\VOCCrop\Flickr2K\Flickr2K\Flickr2K_LR_bicubic\X4
#    (for lmdb)
    dataroot_gt: H:\VOCCrop\Flickr2K\Flickr2K\Flickr2K_train_HR.lmdb
    dataroot_lq: H:\VOCCrop\Flickr2K\Flickr2K\Flickr2K_train_LR\X4.lmdb
    filename_tmpl: '{}'
    io_backend:
      #type: disk
      # (for lmdb)
      type: lmdb

    #gt_size: 192
    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    #num_worker_per_gpu: 3
    #batch_size_per_gpu: 32
    #dataset_enlarge_ratio: 100
    num_worker_per_gpu: 12
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    #pin_memory: ~
  val:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: ./datasets/Set14/GTmod4
    dataroot_lq: ./datasets/Set14/LRbicx4
    io_backend:
      type: disk

# network structures
network_g:
  #type: BSRN
  #num_in_ch: 3
  #num_feat: 64
  #num_block: 8
  #num_out_ch: 3
  #upscale: 4
  #conv: BSConvU
#network_g:
  type: RFDN
  #in_nc: 3
  #nf: 50
  #num_modules: 4
  #out_nc: 3
  #upscale: 4
  

# path
path:
  pretrain_network_g: C:\Users\lzhan\Desktop\sisr\SISR\BSRN\experiments\BSRN_x4\models\net_g_338000.pth
  strict_load_g: True
  resume_state: C:\Users\lzhan\Desktop\sisr\SISR\BSRN\experiments\BSRN_x4\training_states\338000.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  #scheduler:
    #type: CosineAnnealingRestartLR
    #periods: [2000000]
    #restart_weights: [1]
    #eta_min: !!float 1e-7
  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  #total_iter: 2000000
  #warmup_iter: -1  # no warm up

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean


# validation settings
val:
  val_freq: !!float 2e3
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: True

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500